# Postman Integration - Managed by Organization
# This workflow is automatically maintained. Manual changes may be overwritten.
# For configuration options, see: https://github.com/postman-cs/postman-scaffolding

name: Postman Integration
on:
  push:
    branches: [main, master, 'feature/**', 'bugfix/**', 'hotfix/**']
  create:
  pull_request:
    types: [closed]

  # Listen for variable storage from org workflow (advanced setup only)
  repository_dispatch:
    types: [postman-resources-created]

jobs:
  sync:
    if: github.event_name != 'repository_dispatch'
    uses: postman-cs/.github/.github/workflows/postman-sync-org.yml@main
    secrets: inherit

  # Automatically store variables when workspace is created (advanced setup only)
  store-variables:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Store Postman IDs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Storing Postman workspace and collection IDs..."
          gh variable set POSTMAN_WORKSPACE_ID \
            --repo ${{ github.repository }} \
            --body "${{ github.event.client_payload.workspace_id }}"
          gh variable set POSTMAN_MASTER_COLLECTION_ID \
            --repo ${{ github.repository }} \
            --body "${{ github.event.client_payload.master_collection_id }}"
          echo "✓ Variables stored successfully"